# Derived from GitHub's c-cpp.yml file
name: Autoconf CI

on: [push, pull_request]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-suggests --no-install-recommends zlib1g-dev libbz2-dev liblzma-dev libdeflate-dev
    - name: submodule
      run: git submodule update --init
    - name: configure
      run: ./bootstrap; ./configure; # CC="gcc -fsanitize=address"
    - name: make
      run: make
    - name: make check
      run: make check
    #- name: make distcheck
    #  run: make distcheck

  osx-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Homebrew packages
      run: |
        brew update --auto-update
        brew install --overwrite autoconf automake libtool xz
    - name: submodule
      run: git submodule update --init
    - name: configure
      run: ./bootstrap; ./configure CPPFLAGS=-I/opt/homebrew/include
    - name: make
      run: make
    - name: make check
      run: make check
